#' Categorical Variable Distribution - Output Generation
#'
#' Using the tabular output generated by `cvd_process`, this function will build a visualization of the results
#' Each function configuration will output a bespoke ggplot object.
#' Plot theming can be adjusted by the user after the graph has bee output using `+ theme()`.
#' Plots can also be made interactive by using `make_interactive_squba()` on the object output from `cvd_output`.
#'
#' @param process_output *tabular output* | The output from `cvd_process`
#' @param filter_concept *numeric/string or vector* | The specific code(s) that should be the focus of the analysis; used for `ss_anom_la` and `ms_anom_la`
#'
#' @import rlang
#' @returns a graph or table to visualize the results from
#' @export
#'
cvd_output<-function(process_output,
                     filter_concept){
  ## extract output function
  output_function <- process_output %>% collect() %>% distinct(output_function) %>% pull()

  if(output_function=='cvd_ss_exp_cs'){
    cvd_output<-cvd_ss_exp_cs(process_output=process_output)
  }else if(output_function=='cvd_ss_exp_la'){
    cvd_output<-cvd_ss_exp_la(process_output=process_output)
  }else if(output_function=='cvd_ss_anom_la'){
    cvd_output<-cvd_ss_anom_la(process_output=process_output,
                               filt=filter_concept)
  }else if(output_function=='cvd_ms_exp_cs'){
    cvd_output<-cvd_ms_exp_cs(process_output=process_output)
  }else if(output_function=='cvd_ms_exp_la'){
    cvd_output<-cvd_ms_exp_la(process_output=process_output)
  }else if(output_function=='cvd_ms_anom_cs'){
    cvd_output<-cvd_ms_anom_cs(process_output=process_output)
  }else if(output_function=='cvd_ms_anom_la'){
    cvd_output<-cvd_ms_anom_la(process_output=process_output,
                               filt=filter_concept)
  }else(cli::cli_abort('Please enter a valid output_function for this check'))
}
