#' Categorical Variable Distribution - Output Generation
#'
#' Using the tabular output generated by `cvd_process`, this function will build a visualization of the results
#' Each function configuration will output a bespoke ggplot object.
#' Plot theming can be adjusted by the user after the graph has bee output using `+ theme()`.
#' Plots can also be made interactive by using `make_interactive_squba()` on the object output from `cvd_output`.
#'
#' @param process_output *tabular output* | The output from `cvd_process`
#' @param filter_concept *numeric/string or vector* | The specific code(s) that should be the focus of the analysis; used for `ss_anom_la` and `ms_anom_la`
#' @param vocab_tbl *tabular input* | OPTIONAL: the location of an external vocabulary table containing concept names for
#'                  the provided codes. if not NULL, concept names will be available in either a reference
#'                  table or in a hover tooltip
#'
#' @import rlang
#' @import ggplot2
#' @import ggiraph
#' @import gt
#' @importFrom qicharts2 qic
#' @importFrom timetk plot_anomalies
#' @importFrom timetk plot_anomalies_decomp
#'
#'
#' @returns a graph or table to visualize the results from
#'
#' @example inst/example-cvd_process_output.R
#'
#' @export
#'
cvd_output<-function(process_output,
                     filter_concept,
                     vocab_tbl=NULL){
  ## extract output function
  output_function <- process_output %>% collect() %>% distinct(output_function) %>% pull()

  process_output<-join_to_vocabulary(tbl=process_output%>%mutate(concept_id=as.integer(concept_id)),
                               vocab_tbl=vocab_tbl,
                               col='concept_id',
                               vocab_col='concept_id')

  if(output_function=='cvd_ss_exp_cs'){
    cvd_output<-cvd_ss_exp_cs(process_output=process_output)
  }else if(output_function=='cvd_ss_exp_la'){
    cvd_output<-cvd_ss_exp_la(process_output=process_output)
  }else if(output_function=='cvd_ss_anom_la'){
    cvd_output<-cvd_ss_anom_la(process_output=process_output,
                               filt=filter_concept)
  }else if(output_function=='cvd_ms_exp_cs'){
    cvd_output<-cvd_ms_exp_cs(process_output=process_output)
  }else if(output_function=='cvd_ms_exp_la'){
    cvd_output<-cvd_ms_exp_la(process_output=process_output)
  }else if(output_function=='cvd_ms_anom_cs'){
    cvd_output<-cvd_ms_anom_cs(process_output=process_output)
  }else if(output_function=='cvd_ms_anom_la'){
    cvd_output<-cvd_ms_anom_la(process_output=process_output,
                               filt=filter_concept)
  }else(cli::cli_abort('Please enter a valid output_function for this check'))
}
